version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "50000:50000"
      - "8080:8080"
    environment:
      - DOCKER_HOST=tcp://host.docker.internal:2375

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: